<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title><?php echo \Savvy\Base\Registry::getInstance()->get('name'); ?></title>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <meta name="application-name" content="<?php echo \Savvy\Base\Registry::getInstance()->get('name'); ?>" />
    <meta name="application-session-id" content="<?php echo \Savvy\Base\Session::getInstance()->getApplicationSessionId(); ?>" />
    <link rel="stylesheet" type="text/css" href="/default.css" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="icon" href="/favicon.ico" type="image/x-icon" />
  </head>
  <body>
    <script src="<?php echo \Savvy\Base\Registry::getInstance()->get('extjs.cdn', '/js/ext-all.js'); ?>" type="text/javascript"></script>
    <script src="/js/ext-savvy.js" type="text/javascript"></script>
  </body>
</html>
